mysite/mysite/apps/interface/urls.py
from django.conf.urls import url

from .import views

urlpatterns = [
    url(r'^item/(?P<interface_id>\d+)/$', views.InterfaceListPage.as_view(), name='interface_list'),
    url(r'^item/(?P<item_id>\d+)/detail/$', views.InterfaceDetail.as_view(), name='interface_detail'),
    url(r'^item/(?P<item_id>\d+)/update/$', views.InterfaceUpdate.as_view(), name='interface_update')
]

mysite/mysite/apps/urls.py
from django.conf.urls import url

from .import views

urlpatterns = [
    url(r'^home/$', views.HomePage.as_view(), name='index'),
    url(r'^login-success/$', views.InterfaceList.as_view(), name='success'),
    url(r'^logout/$', views.logout_view, name='success'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin_my_site/', include(admin.site.urls)),
    url(r'^interface/', include('mysite.apps.interface.urls', namespace='interface')),
    url(r'^', include('mysite.apps.urls')),
]

mysite/mysite/apps/interface/models.py
#coding=utf-8

from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
class InterfaceEdition(models.Model):

    edition_name = models.CharField(max_length=255, verbose_name='版本名称')
    edition_code = models.IntegerField(verbose_name='版本号', default=0)
    edition_help = models.CharField(max_length=255, verbose_name='帮助', blank=True, null=True)

    def __str__(self):

        return '%s--%s' % (self.edition_name, self.edition_code)

    class Meta:

        unique_together = (("edition_name", "edition_code"),)  # 共同唯一验证



class InterfaceItems(models.Model):

    name = models.CharField(max_length=255, verbose_name='接口名称')
    url = models.CharField(max_length=255, verbose_name='接口地址')
    interface = models.ForeignKey(InterfaceEdition)

    def __str__(self):
        return self.name

    def get_absolute_url(self):

        return reverse('interface:interface_detail', kwargs={'item_id': self.id})


class InterfaceParame(models.Model):

    parame_key = models.CharField(max_length=10, verbose_name='parame key')
    parame_value = models.CharField(max_length=10, verbose_name='parame value')

    item = models.ForeignKey(InterfaceItems)

    def __str__(self):

        return '%s=%s' % (self.parame_key, self.parame_value)

mysite/mysite/apps/models.py
from django.db import models

# Create your models here.

mysite/mysite/apps/forms.py
__author__ = 'sll'
from django.contrib.auth.models import User
from django.forms import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate


class UserForm(AuthenticationForm):

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(['User is not exist!'])
        return username

    def clean(self):

        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if not authenticate(username=username, password=password):
            self._errors['password'] = self.error_class(['Password is error!'])
        return self.cleaned_data

mysite/mysite/apps/interface/forms.py
__author__ = 'sll'
from django.forms.models import inlineformset_factory
from .models import InterfaceItems, InterfaceEdition, InterfaceParame
from django.forms import ModelForm
from django import forms

class InterfaceItemsForm(ModelForm):

    class Meta:
        model = InterfaceItems
        fields = ('name', 'url')

class InterfaceParameForm(ModelForm):

    class Meta:
        model = InterfaceParame
        fields = ('parame_key', 'parame_value')

    def clean_parame_key(self):

        key = self.cleaned_data.get('parame_key')
        if key == 'sss':
            raise forms.ValidationError(['sss is error '])
        return key

InterfaceItemInlineFormSet = inlineformset_factory(InterfaceItems, InterfaceParame, form=InterfaceParameForm, extra=1, max_num=10)

mysite/mysite/apps/interface/views.py
from django.template.response import TemplateResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from .models import InterfaceItems
from django.shortcuts import redirect
from .forms import InterfaceItemsForm, InterfaceItemInlineFormSet

# Create your views here.


class FormsetMixin(object):
    object = None

    def get(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def get_formset_class(self):
        return self.formset_class

    def get_formset(self, formset_class):
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'instance': self.object
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        return redirect(self.object.get_absolute_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))



class InterfaceListPage(ListView):
    template_name = 'interface/list.html'
    model = InterfaceItems

    def get_queryset(self):
        """
        Get the list of items for this view. This must be an iterable, and may
        be a queryset (in which qs-specific behavior will be enabled).
        """
        queryset = super(InterfaceListPage, self).get_queryset()
        return queryset.filter(interface__id=self.kwargs.get('interface_id'))



class InterfaceDetail(DetailView):

    template_name = 'interface/detail.html'
    model = InterfaceItems
    pk_url_kwarg = 'item_id'



class InterfaceUpdate(FormsetMixin, UpdateView):

    template_name = 'interface/update.html'
    model = InterfaceItems
    pk_url_kwarg = 'item_id'
    is_update_view = True
    form_class = InterfaceItemsForm
    formset_class = InterfaceItemInlineFormSet

mysite/mysite/apps/views.py
from django.template.response import TemplateResponse
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from .forms import UserForm
from mysite.apps.interface.models import InterfaceEdition
# Create your views here.

class HomePage(TemplateView):

    template_name = 'home.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(*args, **kwargs)
        form = UserForm(request, request.POST)
        if form.is_valid():
            user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
            if user is not None:
                login(request, user)
                return redirect('/login-success/')
        context['form'] = form
        return self.render_to_response(context)


class InterfaceList(ListView):
    template_name = 'login_success.html'
    model = InterfaceEdition

    def get_context_object_name(self, object_list):
        return super(InterfaceList, self).get_context_object_name(object_list)


def logout_view(request):
    logout(request)
    return redirect('/home/')

mysite/mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My Web</title>
  <script type="application/javascript" src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
</head>
<body>
<div style="text-align: center">
  <div style="background: green; height: 50px; padding: 10px;">
    {% if request.user.is_authenticated %}username: {{ request.user }} <a href="/logout/" style="color: black;">注销</a> {% endif %}
  </div>
  <h1>My Web</h1>
  <h3>This is interface control web!</h3>
  {% block content %}
  {% endblock content %}
</div>
</body>
</html>

mysite/mysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <div style="margin-top: 50px;">
    <form method="post">{% csrf_token %}
      <span style="margin-left: 5px; color: red;">{{ form.errors.username.0 }}</span><br>
      <label for="id_username">User Name: </label><input type="text" name="username" id="id_username"><br><br>
      <span style="margin-left: 5px; color: red;">{{ form.errors.password.0 }}</span><br>
      <label for="id_password">Pass Word: </label><input type="password" name="password" id="id_password"><br><br>
      <input type="submit" value=" submit ">&nbsp;
      <input type="button" value=" cancel">
    </form>
  </div>
{% endblock content %}

mysite/mysite/templates/interface/detail.html
{% extends 'base.html' %}

{% block content %}
<style>
td{border:solid #add9c0; border-width:0px 1px 1px 0px; padding:5px 0px;}
table{border:solid #add9c0; border-width:1px 0px 0px 1px;}
</style>
<div  style="text-align: center">
  <a href="{% url 'interface:interface_update' item_id=object.id %}"><span>{{ object.name }}</span><br><br></a>
  <span>{{ object.url }}</span><br><br>
  参数：<table width="610" align="center">
    <thead>
    </thead>
    <tbody>
     <tr>
    {% for o in object.interfaceparame_set.all %}
      <td width="200">{{ o.parame_key }}</td>
    {% endfor %}
    </tr>
     <tr>
    {% for o in object.interfaceparame_set.all %}
      <td width="200">{{ o.parame_value }}</td>
    {% endfor %}
     </tr>
    </tbody>
  </table>
</div>
{% endblock %}

mysite/mysite/templates/interface/list.html
{%  extends 'base.html' %}

{% block content %}
<style>
td{border:solid #add9c0; border-width:0px 1px 1px 0px; padding:5px 0px;}
table{border:solid #add9c0; border-width:1px 0px 0px 1px;}
</style>
<div  style="text-align: center">
  <table width="610" align="center">
    <thead>
    <tr>
      <td width="200">接口名称</td>
      <td width="200">状态</td>
      <td width="200">描述</td>
    </tr>
    </thead>
    <tbody>
    {% for o in object_list %}
    <tr>
      <td><a href="{% url 'interface:interface_detail' item_id=o.id %}">{{ o.name }}</a></td>
      <td><a href="{% url 'interface:interface_detail' item_id=o.id %}">查看</a></td>
      <td>{{ o.url }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

mysite/mysite/templates/interface/update.html
{% extends "base.html" %}


{% block content %}
<style type="text/css">
  .errorlist {
    list-style: none;
    color: #B94A48;
    margin: 0px 0px 9px 0px;
    padding: 0px;
  }
</style>

<script type="text/html" id="book-template">
  <div id="book-__prefix__">
    {{ formset.empty_form }}
  </div>
</script>

<div class="page-header">
  <h1>{% if form.instance.pk %}Edit{% else %}Add{% endif %} Author and Books</h1>
</div>

<form action="." method="post">
  {% csrf_token %}
  <legend style="text-align: center">InterfaceItem</legend>
  <div class="author">
    {{ form.as_p }}
  </div>

  <legend>
    <div class="pull-right"><a href="javascript:void(0);" class="btn btn-inverse add-book"><i class="icon-plus icon-white"></i> Add parame</a></div>
    Parame
  </legend>
  <div class="books form-inline">
    {{ formset.management_form }}
    {% for form in formset %}
    {{ form.as_p }}
    {% endfor %}
  </div>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>

<script type="application/javascript">
    $('.add-book').click(function(ev){
      var count = parseInt($('#id_interfaceparame_set-TOTAL_FORMS').attr('value'), 10);
      var tmplMarkup = $('#book-template').html();
      var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count)
      console.log(compiledTmpl);
      $('div.books').append(compiledTmpl)
      alert(count)
      var total = count + 1
      $('#id_interfaceparame_set-TOTAL_FORMS').attr('value', total);
      alert($('#id_interfaceparame_set-TOTAL_FORMS').attr('value'))
    });
</script>


{% endblock content %}

mysite/mysite/templates/login_success.html
{% extends 'base.html' %}

{% block content %}
<style>
td{border:solid #add9c0; border-width:0px 1px 1px 0px; padding:5px 0px;}
table{border:solid #add9c0; border-width:1px 0px 0px 1px;}
</style>
<div  style="text-align: center">
  <table width="610" align="center">
    <thead>
    <tr>
      <td width="200">名称</td>
      <td width="200">版本</td>
      <td width="200">描述</td>
    </tr>
    </thead>
    <tbody>
    {% for o in object_list %}
    <tr>
      <td><a href="{% url 'interface:interface_list' interface_id=o.id %}">{{ o.edition_name }}</a></td>
      <td>{{ o.edition_code }}</td>
      <td>{{ o.edition_help }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}